---
title: "PASSNYC PREPROCESS"
author: "Manoranjan Kumar"
date: "7/23/2018"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
getwd()
setwd("~/Desktop/PASSNYC")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(cache=TRUE)
hook1 <- function(x){ gsub("```\n*```r*\n*", "", x) }
hook3 <- function(x){ gsub("```\n+```\n", "", x) }
hook3 <- function(x){ gsub("```\n+```\n", "", gsub("```\n*```r*\n*", "", x)) }
hook4 <- function(x){ gsub("```\n+```\n", "",  gsub("message", "", x)) }
knitr::knit_hooks$set(document = hook4)
```


```{r}
library(readr)
SchoolMain_ori <- read.csv("https://raw.githubusercontent.com/manusatx/NYC_SCHOOLS/master/2016%20School%20Explorer_Reduced.csv")
#check number iof rows and columns
SchoolMain <- SchoolMain_ori
dim(SchoolMain)
#Look at data by using summary
#summary(SchoolMain)
#str(SchoolMain)
```
```{r}
#Calculate Number of libraries for each school in 1 mile radius.
LibraryMain <- read.csv("https://raw.githubusercontent.com/manusatx/NYC_SCHOOLS/master/LIBRARY.csv")
LibraryMain$LLongitude <- as.numeric(gsub("\\(|\\]", "", sapply(strsplit(as.character(LibraryMain$the_geom),split=" ", fixed=TRUE), "[[", 2)))
LibraryMain$LLatitude <- as.numeric(gsub("\\)|\\]", "", sapply(strsplit(as.character(LibraryMain$the_geom),split=" ", fixed=TRUE), "[[", 3)))
#str(LibraryMain)

distREUSEfunc <- function(xlon, xlat, mileradius, inputrefdata) {
  library(geosphere)
  #Make sure inputrefdata has columns LLongitude and LLatitude
  tempmilelist <- as.list(as.matrix(by(inputrefdata, 1:nrow(inputrefdata), function(row) { distHaversine(c(row$LLongitude, row$LLatitude), c(xlon,xlat))  })/1600))
  idx <-   which(tempmilelist < mileradius)
  as.numeric(length(tempmilelist[idx]))
}

LibrarySub <- LibraryMain[,c("LLatitude", "LLongitude","SYSTEM", "NAME","ZIP")]

library(dplyr)
SchoolMain <- SchoolMain %>%
mutate(numoflibraries <- by(SchoolMain, 1:nrow(SchoolMain), function(row) { distREUSEfunc(row$Longitude, row$Latitude,1,LibrarySub)}))

colnames(SchoolMain)[ncol(SchoolMain)] <- "NumOfLibraries"

SchoolMain$NumOfLibraries <- as.numeric(SchoolMain$NumOfLibraries)
```

```{r}
# After School Programs
#https://data.cityofnewyork.us/Social-Services/After-School-Programs/6ej9-7qyi

AfterSchoolPrograms <- read.csv("https://raw.githubusercontent.com/manusatx/NYC_SCHOOLS/master/DOITT_AFTER_SCHOOL_PROGRAM_01_29JUL2009.csv")
AfterSchoolPrograms$LLongitude <- as.numeric(gsub("\\(|\\]", "", sapply(strsplit(as.character(AfterSchoolPrograms$the_geom),split=" ", fixed=TRUE), "[[", 2)))
AfterSchoolPrograms$LLatitude <- as.numeric(gsub("\\)|\\]", "", sapply(strsplit(as.character(AfterSchoolPrograms$the_geom),split=" ", fixed=TRUE), "[[", 3)))

AfterSchoolProgramsSub <- AfterSchoolPrograms[,c("LLatitude", "LLongitude","SCHOOL_ID", "SITE_NAME","SITE_ZIP")]

SchoolMain <- SchoolMain %>%
mutate(numofaftschprogs <- by(SchoolMain, 1:nrow(SchoolMain), function(row) { distREUSEfunc(row$Longitude, row$Latitude,1,AfterSchoolProgramsSub)}))

colnames(SchoolMain)[ncol(SchoolMain)] <- "NumOfAfterSchoolProgs"
```

```{r}
#Number of subsidized housing units
#https://data.cityofnewyork.us/Housing-Development/Affordable-Housing/x9h2-i4fk/data
AffordableHousing <- read.csv("https://raw.githubusercontent.com/manusatx/NYC_SCHOOLS/master/Affordable_Housing.csv")
#Filter units and keep where Extremely.Low.Income.Units or Very.Low.Income.Units is not 0
AffordableHousing <- subset(AffordableHousing ,Extremely.Low.Income.Units != "0" 
                            | Very.Low.Income.Units != "0")
AffordableHousing <- subset(AffordableHousing, select=c(Latitude..Internal.,Longitude..Internal.,Extremely.Low.Income.Units,Very.Low.Income.Units))

colnames(AffordableHousing) <- c("LLatitude","LLongitude","Extemecount","Lowcount")
#add the Extreme count and Low count
AffordableHousing <- as.data.frame(cbind(AffordableHousing$LLatitude,AffordableHousing$LLongitude,as.numeric(AffordableHousing$Extemecount)+as.numeric(AffordableHousing$Lowcount)))
colnames(AffordableHousing) <- c("LLatitude","LLongitude","LowIncomeUnits")
# remove the unknown locations.
AffordableHousing <- AffordableHousing[complete.cases(AffordableHousing), ]

SchoolMain <- SchoolMain %>%
mutate(LowIncomeUnits <- by(SchoolMain, 1:nrow(SchoolMain), function(row) { distREUSEfunc(row$Longitude, row$Latitude,1,AffordableHousing)}))

colnames(SchoolMain)[ncol(SchoolMain)] <- "NumOfLowIncomeUnits"

```

```{r}
# Median household income in census tract
# Manhattan - New York County
# Bronx - Bronx County
# Brooklyn - Kings County
# Queens - Queens County
# Staten Island - Richmond County
library(tidycensus)
#Check the available variables
censusvars <- load_variables(2016, "acs5", cache = TRUE)
#censusvars[grepl(paste(c("child.*poverty", "poverty.*child"), collapse="|"), ignore.case = TRUE, censusvars$label), ]
#View(censusvars)
#censusvars[grepl("PERCENT*BELOW POVERTY LEVEL", ignore.case = TRUE, censusvars$label), ]
#income by census tract
census_api_key('e60abe11e6232c67560aedf4c3cda7b293e5ea75')
Manhattan <- get_acs(geography = "tract", variables = "B19013_001",
state = "NY", county = "New york", geometry = TRUE)
Bronx <- get_acs(geography = "tract", variables = "B19013_001",
state = "NY", county = "Bronx", geometry = TRUE)
Queens <- get_acs(geography = "tract", variables = "B19013_001",
state = "NY", county = "Queens", geometry = TRUE)
Brooklyn <- get_acs(geography = "tract", variables = "B19013_001",
state = "NY", county = "Kings", geometry = TRUE)
Staten <- get_acs(geography = "tract", variables = "B19013_001",
state = "NY", county = "Richmond", geometry = TRUE)
NYC_income <- rbind(Manhattan,Bronx,Queens,Brooklyn,Staten)
NYC_income <- as.data.frame(NYC_income)
NYC_income <- subset(NYC_income, select=-c(NAME,variable,moe,geometry))
colnames(NYC_income) <- c("GEOID","MedianHldIncome")

library(censusr)
SchoolMain$SchoolGEOID  <- apply(SchoolMain, 1, function(row) call_geolocator_latlon(row['Latitude'], row['Longitude']))
#mapply(call_geolocator_latlon,SchoolMain$Latitude, SchoolMain$Longitude )
#Remove last 4 characters to get census tract GEOID of each school
SchoolMain$GEOID<- substr(SchoolMain$SchoolGEOID ,1,nchar(SchoolMain$SchoolGEOID)-4)
#merge income to schoolmain
SchoolMain <- merge(SchoolMain, NYC_income, by="GEOID", all.x=TRUE)

```



```{r}
# ratio of income to poverty in census tract
# B17026 - ratio of income to poverty of families
library(tidycensus)
census_api_key('e60abe11e6232c67560aedf4c3cda7b293e5ea75')
Manhattan_inc <- get_acs(geography = "tract", variables = "B17026_001",
state = "NY", county = "New york", geometry = TRUE)
Bronx_inc <- get_acs(geography = "tract", variables = "B17026_001",
state = "NY", county = "Bronx", geometry = TRUE)
Queens_inc <- get_acs(geography = "tract", variables = "B17026_001", 
state = "NY", county = "Queens", geometry = TRUE)
Brooklyn_inc <- get_acs(geography = "tract", variables = "B17026_001",
state = "NY", county = "Kings", geometry = TRUE)
Staten_inc <- get_acs(geography = "tract", variables = "B17026_001",
state = "NY", county = "Richmond", geometry = TRUE)
NYC_incPRatio <- rbind(Manhattan_inc,Bronx_inc,Queens_inc,Brooklyn_inc,Staten_inc)
NYC_incPRatio <- as.data.frame(NYC_incPRatio)
NYC_incPRatio <- subset(NYC_incPRatio, select=-c(NAME,variable,moe,geometry))
colnames(NYC_incPRatio) <- c("GEOID","IncomeToPovertyRatio")

SchoolMain <- merge(SchoolMain, NYC_incPRatio, by="GEOID", all.x=TRUE)
```

```{r}
# B17006 - child poverty (under 18 years of age)
#https://www.socialexplorer.com/data/ACS2015_5yr/metadata/?ds=ACS15_5yr&table=B17006

library(tidycensus)
census_api_key('e60abe11e6232c67560aedf4c3cda7b293e5ea75')
Manhattan_cp <- get_acs(geography = "tract", variables = "B17006_001", 
state = "NY", county = "New york", geometry = TRUE)
Bronx_cp <- get_acs(geography = "tract", variables = "B17006_001",
state = "NY", county = "Bronx", geometry = TRUE)
Queens_cp <- get_acs(geography = "tract", variables = "B17006_004",
state = "NY", county = "Queens", geometry = TRUE)
Brooklyn_cp <- get_acs(geography = "tract", variables = "B17006_001",
state = "NY", county = "Kings", geometry = TRUE)
Staten_cp <- get_acs(geography = "tract", variables = "B17006_001",
state = "NY", county = "Richmond", geometry = TRUE)
NYC_cp <- rbind(Manhattan_cp,Bronx_cp,Queens_cp,Brooklyn_cp,Staten_cp)
NYC_cp <- as.data.frame(NYC_cp)
NYC_cp <- subset(NYC_cp, select=-c(NAME,variable,moe,geometry))
colnames(NYC_cp) <- c("GEOID","ChildPoverty")

SchoolMain <- merge(SchoolMain, NYC_cp, by="GEOID", all.x=TRUE)
```

```{r}
# B22003 - Food stamps received  
#https://www.socialexplorer.com/data/ACS2015_5yr/metadata/?ds=ACS15_5yr&table=B22003

library(tidycensus)
census_api_key('e60abe11e6232c67560aedf4c3cda7b293e5ea75')
Manhattan_snap <- get_acs(geography = "tract", variables = "B22003_001", 
state = "NY", county = "New york", geometry = TRUE)
Bronx_snap <- get_acs(geography = "tract", variables = "B22003_001",
state = "NY", county = "Bronx", geometry = TRUE)
Queens_snap <- get_acs(geography = "tract", variables = "B22003_004",
state = "NY", county = "Queens", geometry = TRUE)
Brooklyn_snap <- get_acs(geography = "tract", variables = "B22003_001",
state = "NY", county = "Kings", geometry = TRUE)
Staten_snap <- get_acs(geography = "tract", variables = "B22003_001",
state = "NY", county = "Richmond", geometry = TRUE)
NYC_snap <- rbind(Manhattan_snap,Bronx_snap,Queens_snap,Brooklyn_snap,Staten_snap)
NYC_snap <- as.data.frame(NYC_snap)
NYC_snap <- subset(NYC_snap, select=-c(NAME,variable,moe,geometry))
colnames(NYC_snap) <- c("GEOID","CountofSNAPHlds")

SchoolMain <- merge(SchoolMain, NYC_snap, by="GEOID", all.x=TRUE)
```

```{r}
# C27016 - health insurance coverage
#https://www.socialexplorer.com/data/ACS2015_5yr/metadata/?ds=ACS15_5yr&table=C27016

library(tidycensus)
census_api_key('e60abe11e6232c67560aedf4c3cda7b293e5ea75')
Manhattan_hcov <- get_acs(geography = "tract", variables = "C27016_001", 
state = "NY", county = "New york", geometry = TRUE)
Bronx_hcov <- get_acs(geography = "tract", variables = "C27016_001",
state = "NY", county = "Bronx", geometry = TRUE)
Queens_hcov <- get_acs(geography = "tract", variables = "C27016_001",
state = "NY", county = "Queens", geometry = TRUE)
Brooklyn_hcov <- get_acs(geography = "tract", variables = "C27016_001",
state = "NY", county = "Kings", geometry = TRUE)
Staten_hcov <- get_acs(geography = "tract", variables = "C27016_001",
state = "NY", county = "Richmond", geometry = TRUE)
NYC_hcov <- rbind(Manhattan_hcov,Bronx_hcov,Queens_hcov,Brooklyn_hcov,Staten_hcov)
NYC_hcov <- as.data.frame(NYC_hcov)
NYC_hcov<- subset(NYC_hcov, select=-c(NAME,variable,moe,geometry))
colnames(NYC_hcov) <- c("GEOID","HealthCoverage")

SchoolMain <- merge(SchoolMain, NYC_hcov, by="GEOID", all.x=TRUE)
```

```{r}
#At this point save the file in an excel sheet for reuse
write.csv(SchoolMain, file = "SchoolMain.csv")
```